### ISSUE TITLE
DB File

### ISSUE THREAD

**Issue by Amanlte** [KryptonB/inventory-management-system#1]
Where is the DB file or table details?

**Comment by KryptonB** [comment]
Sorry for the delay. Was stuck with some work :) 
Uploaded the DB file shop_inventory.sql under  /inc/config
You can take it from there.
Follow below steps before exporting the file
1.	Create a new blank DB in XAMPP called shop_inventory
2.	Create a new user called inventoryUser and password as **_password_** . and give full permission to that user.
3.	Load the sql dump to the newly created shop_inventory database 
4.	Change the root url of your website path in /inc/config/constants.php  file

**Comment by KryptonB** [comment]
Once you load the data, you can use the default user _**guest**_ with the password **_1234_** to login to the site.

**Comment by KryptonB** [comment]
Closing the issue as the file has been added to the repo
