### ISSUE TITLE
issues with jquery

### ISSUE THREAD

**Issue by ilovefood2** [KryptonB/inventory-management-system#3]
I am trying to use this ajax query
`https://datatables.net/examples/server_side/simple.html`

basically I added following to footer.php
```
<script type="text/javascript"  src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script type="text/javascript"  src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
    $(document).ready(function() {
        $('#itemDetailsTable').DataTable( {
            "processing": true,
            "serverSide": true,
            "order": [[ 0, "asc" ]],
            "ajax": "./inc/process.php"
        } );
    } );
    </script>
```

then datatable disappeared on index.php, i did a little try&error and found out, jquery-3.3.1.js seems conflicts with existing  `<script src="vendor/jquery/jquery.min.js"></script>`

do you know any way to get around this? 

thanks

**Comment by ilovefood2** [comment]
i guess what im trying to find out is how does `itemDetailsTable` is linked and shown on index page

**Comment by KryptonB** [comment]
Closing the issue
